# Generated by Django 4.1.5 on 2023-01-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0001_initial'),
    ]

    operations = [
    ]
