# Generated by Django 4.1.5 on 2023-02-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualaid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
